# Generated by Django 6.0.5 on 2026-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='teacher',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.CharField(choices=[('Tiểu học', 'Tiểu học'), ('THCS', 'THCS'), ('THPT', 'THPT'), ('Đại học', 'Đại học')], default='THPT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='permission',
            field=models.CharField(choices=[('view', 'Chỉ xem'), ('download', 'Xem và tải')], default='download', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(default='Toán', max_length=100),
            preserve_default=False,
        ),
    ]
