# Generated by Django 6.0.5 on 2026-06-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_document_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='level',
            field=models.CharField(choices=[('Tiểu học', 'Tiểu học'), ('THCS', 'THCS'), ('THPT', 'THPT'), ('Đại học', 'Đại học')], default='THPT', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(default='khác', max_length=100),
        ),
    ]
