# Generated by Django 5.2.6 on 2026-07-16 16:08

import materials.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=materials.storage.DocumentCloudinaryStorage(), upload_to='documents/'),
        ),
    ]
