# Generated by Django 6.0.5 on 2026-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số lượt làm tối đa'),
        ),
    ]
