# Generated by Django 6.0.5 on 2026-05-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('quiz', '0006_remove_quizresult_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
