# Generated by Django 5.2.6 on 2026-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_choice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
