# Generated by Django 6.0.5 on 2026-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
