# Generated by Django 6.0.5 on 2026-05-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_ai', '0005_alter_quiz_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='total_questions',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
