# Generated by Django 6.0.5 on 2026-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='teacher',
            new_name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='teacher', max_length=20),
            preserve_default=False,
        ),
    ]
