# Generated by Django 6.0.5 on 2026-05-21 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('todo', '0002_rename_teacher_todo_user_todo_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='todo_submissions/'),
        ),
        migrations.AddField(
            model_name='todo',
            name='submission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='role',
            field=models.CharField(choices=[('teacher', 'Giáo viên'), ('student', 'Học sinh')], max_length=20),
        ),
    ]
