# Generated by Django 6.0.5 on 2026-05-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_options_todo_assigned_by_todo_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
