# Generated by Django 6.0.5 on 2026-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_personaltodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltodo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Công khai'),
        ),
    ]
