# Generated by Django 6.0.5 on 2026-05-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_personaltodo_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltodo',
            old_name='student',
            new_name='user',
        ),
        migrations.AddField(
            model_name='personaltodo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
