# Generated by Django 6.0.5 on 2026-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_student_personaltodo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltodo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
