# Generated by Django 6.0.5 on 2026-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Học sinh'), ('teacher', 'Giáo viên'), ('admin', 'Quản trị')], default='student', max_length=20),
        ),
    ]
