# Generated by Django 6.0.5 on 2026-05-30 02:27

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, default=courses.models.generate_course_code, max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
