# Generated by Django 5.2.6 on 2026-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_join_permission_choices_coursemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='join_permission',
            field=models.CharField(choices=[('public', 'Công khai'), ('approval', 'Yêu cầu kiểm duyệt')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã chấp nhận'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
