# Generated by Django 6.0.5 on 2026-05-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('courses', '0002_alter_course_course_code_delete_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='join_permission',
            field=models.CharField(choices=[('free', 'Tự do'), ('invite', 'Cần mã mời')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='max_members',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
