# Generated by Django 6.0.5 on 2026-05-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_course_classroom_join_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
