# Generated by Django 6.0.5 on 2026-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroommember_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='join_permission',
            field=models.CharField(choices=[('free', 'Công khai'), ('approval', 'Yêu cầu kiểm duyệt')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroommember',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã chấp nhận'), ('rejected', 'Từ chối')], default='approved', max_length=20),
        ),
    ]
